version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
    networks:
        - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge
volumes:  
  rabbitmq_data:
  rabbitmq_logs: